language: node_js
os: osx
node_js: 6
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn run lint
- yarn run compile
deploy:
  provider: script
  script: upload-sourcemaps.sh
  on:
    tags: true
